### ISSUE TITLE
可以参照官方指南安装依赖而不是自己去找

### ISSUE THREAD

**Issue by SekiBetu** [Jrohy/python3-install#5]
https://devguide.python.org/setup/#linux

https://github.com/Jrohy/python3-install/blob/922180f55bf3631a6484aeedc1ab2d031af06476/install.sh#L82

比如可以使用

```shell
sudo apt build-dep python3
sudo apt install pkg-config
```

安装所有基础依赖

**Comment by Jrohy** [comment]
我测试下

**Comment by SekiBetu** [comment]
> 我测试下

openssl 的版本号也希望用参数传递进去而不是写死在里面，去年 python3.9, 3.10, 3.11 等版本已经和 openssl 3.0 版本适配:
https://github.com/python/cpython  83001 号 issue

**Comment by Jrohy** [comment]
安装依赖的暂时不改动，兼容旧系统
